runtime: python37
entrypoint: python tornado_main.py
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
  - url: /ws
    secure: always
    script: auto
    http_headers:
      Connection-Header: Upgrade
      Upgrade-Header: websocket
