runtime: python37
entrypoint: python tornado_main.py
handlers:
  - url: /static/.*
    static_dir: static

    #secure: always
  - url: /.*
    #secure: always
    redirect_http_response_code: 301
    script: auto
