name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r requirements.txt
      - name: Lint with black
        run: |
          black . --check
      - name: Test with pytest
        run: |
          coverage run --source='.' manage.py test
          coverage xml
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          # User defined upload name. Visible in Codecov UI
          name: SC-test
          # Repository upload token - get it from codecov.io
          token: ${{ secrets.CODECOV_TOKEN }}
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true
          file: coverage.xml
          yml: .codecov.yml

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get install gettext
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: prepare
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          python manage.py migrate
          python manage.py data
          python manage.py compilemessages
          python manage.py createcachetable
          python manage.py collectstatic
      - name: auth gcp
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "285.0.0"
          project_id: ${{ secrets.gcp_project_id }}
          service_account_email: ${{ secrets.gcp_email }}
          service_account_key: ${{ secrets.gcp_key }}
          export_default_credentials: true
      - name: Publish app to Google App Engine
        run: |
          # This client-secret.json is converted by GCP_SA_KEY.
          gcloud auth activate-service-account ${{ secrets.gcp_email }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.gcp_project_id }}
          gcloud -q app deploy app.yaml --promote
